#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# License audit (tasks T-002 / T-003):
#  1. every first-party source file starts with the SPDX header;
#  2. every resolved pub dependency has a LICENSE whose text matches the
#     allow-list; the result is written to THIRD_PARTY.md.
# Usage: tools/license_audit.sh   (from the repository root)
set -euo pipefail
cd "$(dirname "$0")/.."

PUB_CACHE="${PUB_CACHE:-$HOME/.pub-cache}"
FLUTTER_ROOT="${FLUTTER_ROOT:-$(dirname "$(dirname "$(command -v flutter)")")}"
failures=0

echo "== SPDX headers"
while IFS= read -r f; do
  if ! head -n 1 "$f" | grep -q 'SPDX-License-Identifier: AGPL-3.0-or-later'; then
    echo "missing SPDX header: $f"
    failures=$((failures + 1))
  fi
done < <(find app/lib app/test packages tools -name '*.dart' -not -path '*/generated/*' -not -path '*/.dart_tool/*' -not -path '*/build/*')

echo "== Dependencies (pubspec.lock)"
# Match a license file's text against the allow-list by characteristic phrases.
classify() {
  local file="$1"
  if grep -qi 'Apache License' "$file"; then echo "Apache-2.0"
  elif grep -qi 'Mozilla Public License' "$file"; then echo "MPL-2.0"
  elif grep -qi 'GNU AFFERO GENERAL PUBLIC LICENSE' "$file"; then echo "AGPL-3.0"
  elif grep -qi 'GNU LESSER GENERAL PUBLIC LICENSE' "$file"; then echo "LGPL"
  elif grep -qi 'GNU GENERAL PUBLIC LICENSE' "$file"; then
    if grep -q 'Version 3' "$file"; then echo "GPL-3.0"; else echo "GPL-2.0"; fi
  elif grep -qi 'Redistribution and use in source and binary forms' "$file"; then echo "BSD"
  elif grep -qi 'Permission is hereby granted, free of charge' "$file"; then echo "MIT"
  elif grep -qi 'Permission to use, copy, modify, and/or distribute this software for any purpose' "$file"; then echo "ISC"
  elif grep -qi 'This is free and unencumbered software' "$file"; then echo "Unlicense"
  elif grep -qi 'CC0' "$file"; then echo "CC0"
  elif grep -qi 'altered source versions must be plainly marked' "$file"; then echo "Zlib"
  else echo "UNKNOWN"; fi
}

allowed='^(Apache-2\.0|MPL-2\.0|AGPL-3\.0|LGPL|GPL-3\.0|BSD|MIT|ISC|Unlicense|CC0|Zlib)$'

{
  echo "# Third-party licenses"
  echo
  echo "Generated by \`tools/license_audit.sh\`. All entries must be AGPL-3.0-compatible."
  echo
  echo "| Package | Version | License | Source |"
  echo "|---|---|---|---|"
} > THIRD_PARTY.md

# Parse pubspec.lock into "name|version|source|path" lines.
list_packages() {
  python3 - "$PUB_CACHE" "$FLUTTER_ROOT" <<'PYEOF'
import re, sys, os
pub_cache, flutter_root = sys.argv[1], sys.argv[2]
text = open('pubspec.lock').read()
for name, body in re.findall(r'\n  ([A-Za-z0-9_]+):\n((?:    .*\n)+)', text):
    src = re.search(r'source: (\S+)', body)
    ver = re.search(r'version: "([^"]+)"', body)
    src = src.group(1) if src else '?'
    ver = ver.group(1) if ver else '?'
    if src == 'hosted':
        path = os.path.join(pub_cache, 'hosted', 'pub.dev', f'{name}-{ver}')
    elif src == 'sdk':
        path = os.path.join(flutter_root, 'packages', name)
    elif src == 'path':
        m = re.search(r'path: "([^"]+)"', body)
        path = m.group(1) if m else ''
    else:
        path = ''
    print(f'{name}|{ver}|{src}|{path}')
PYEOF
}

while IFS='|' read -r name version source path; do
  if [ "$source" = "path" ]; then
    lic="AGPL-3.0 (first-party)"
  else
    licfile=$(ls "$path"/LICENSE* "$path"/license* 2>/dev/null | head -n1 || true)
    # SDK packages are covered by the Flutter SDK's root LICENSE (BSD-3).
    if [ -z "$licfile" ] && [ "$source" = "sdk" ]; then licfile="$FLUTTER_ROOT/LICENSE"; fi
    if [ -z "$licfile" ]; then
      lic="UNKNOWN (no LICENSE file)"
    else
      lic=$(classify "$licfile")
    fi
    if ! [[ "$lic" =~ $allowed ]]; then
      echo "NOT ALLOWED: $name $version -> $lic ($path)"
      failures=$((failures + 1))
    fi
  fi
  echo "| $name | $version | $lic | $source |" >> THIRD_PARTY.md
done < <(list_packages)

if [ "$failures" -ne 0 ]; then
  echo "license audit: $failures problem(s)"
  exit 1
fi
echo "license audit: ok (see THIRD_PARTY.md)"
